# Generated by Django 4.2.30 on 2026-04-27 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('summary', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Resumen de documento',
                'verbose_name_plural': 'Resúmenes de documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(default=list)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('compared_with', models.ManyToManyField(blank=True, related_name='compared_in', to='app.documentsummary')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_requests', to='app.documentsummary')),
            ],
            options={
                'verbose_name': 'Solicitud de similitud',
                'verbose_name_plural': 'Solicitudes de similitud',
                'ordering': ['-requested_at'],
            },
        ),
    ]
